[2024-04-13T01:28:27.594+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 12345678.init_qdrant manual__2024-04-12T20:34:20.315543+00:00 [queued]>
[2024-04-13T01:28:27.600+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 12345678.init_qdrant manual__2024-04-12T20:34:20.315543+00:00 [queued]>
[2024-04-13T01:28:27.600+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-04-13T01:28:27.610+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): init_qdrant> on 2024-04-12 20:34:20.315543+00:00
[2024-04-13T01:28:27.614+0000] {standard_task_runner.py:60} INFO - Started process 2928 to run task
[2024-04-13T01:28:27.620+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '12345678', 'init_qdrant', 'manual__2024-04-12T20:34:20.315543+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpm9exs0lz']
[2024-04-13T01:28:27.622+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask init_qdrant
[2024-04-13T01:28:27.657+0000] {task_command.py:423} INFO - Running <TaskInstance: 12345678.init_qdrant manual__2024-04-12T20:34:20.315543+00:00 [running]> on host 5feba290cccc
[2024-04-13T01:28:27.723+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='12345678' AIRFLOW_CTX_DAG_ID='12345678' AIRFLOW_CTX_TASK_ID='init_qdrant' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T20:34:20.315543+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T20:34:20.315543+00:00'
[2024-04-13T01:28:27.895+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `12345678` already exists!"},"time":0.112063167}\''}
[2024-04-13T01:28:27.916+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=12345678, task_id=init_qdrant, execution_date=20240412T203420, start_date=20240413T012827, end_date=20240413T012827
[2024-04-13T01:28:27.963+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-13T01:28:27.981+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
