[2024-04-12T18:22:59.438+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 12345678.4567 manual__2024-04-12T18:22:56.007246+00:00 [queued]>
[2024-04-12T18:22:59.452+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 12345678.4567 manual__2024-04-12T18:22:56.007246+00:00 [queued]>
[2024-04-12T18:22:59.453+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-12T18:22:59.491+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 4567> on 2024-04-12 18:22:56.007246+00:00
[2024-04-12T18:22:59.506+0000] {standard_task_runner.py:60} INFO - Started process 301 to run task
[2024-04-12T18:22:59.531+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '12345678', '4567', 'manual__2024-04-12T18:22:56.007246+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp2v2jc07g']
[2024-04-12T18:22:59.539+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask 4567
[2024-04-12T18:22:59.615+0000] {task_command.py:423} INFO - Running <TaskInstance: 12345678.4567 manual__2024-04-12T18:22:56.007246+00:00 [running]> on host 066a79a1baa5
[2024-04-12T18:22:59.703+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='12345678' AIRFLOW_CTX_DAG_ID='12345678' AIRFLOW_CTX_TASK_ID='4567' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T18:22:56.007246+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T18:22:56.007246+00:00'
[2024-04-12T18:22:59.738+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 404 (Not Found)\nRaw response content:\nb\'{"status":{"error":"Not found: Collection `12345678` doesn\\\'t exist!"},"time":0.002019542}\''}
[2024-04-12T18:22:59.770+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=12345678, task_id=4567, execution_date=20240412T182256, start_date=20240412T182259, end_date=20240412T182259
[2024-04-12T18:22:59.789+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-12T18:22:59.803+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
