[2024-04-12T20:33:49.387+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 12345678.count manual__2024-04-12T20:33:46.009890+00:00 [queued]>
[2024-04-12T20:33:49.397+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 12345678.count manual__2024-04-12T20:33:46.009890+00:00 [queued]>
[2024-04-12T20:33:49.403+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-12T20:33:49.436+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): count> on 2024-04-12 20:33:46.009890+00:00
[2024-04-12T20:33:49.449+0000] {standard_task_runner.py:60} INFO - Started process 2015 to run task
[2024-04-12T20:33:49.459+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '12345678', 'count', 'manual__2024-04-12T20:33:46.009890+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpv971evqg']
[2024-04-12T20:33:49.464+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask count
[2024-04-12T20:33:49.553+0000] {task_command.py:423} INFO - Running <TaskInstance: 12345678.count manual__2024-04-12T20:33:46.009890+00:00 [running]> on host 5feba290cccc
[2024-04-12T20:33:49.671+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='12345678' AIRFLOW_CTX_DAG_ID='12345678' AIRFLOW_CTX_TASK_ID='count' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T20:33:46.009890+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T20:33:46.009890+00:00'
[2024-04-12T20:33:49.741+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 404 (Not Found)\nRaw response content:\nb\'{"status":{"error":"Not found: Collection `12345678` doesn\\\'t exist!"},"time":0.000066}\''}
[2024-04-12T20:33:49.782+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=12345678, task_id=count, execution_date=20240412T203346, start_date=20240412T203349, end_date=20240412T203349
[2024-04-12T20:33:49.814+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-12T20:33:49.841+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
